TheBlog/config/routes.rb
Rails.application.routes.draw do

  resources :photos

resources :users

  resources :articles do 
    resources :comments
  end

  root 'static_pages#home'

  get 'static_pages/home' => 'static_pages#home'
  get 'Israa' => 'static_pages#Israa'
  get 'Karim' => 'static_pages#Karim'
  get 'Merna' => 'static_pages#Merna'
  get 'Mina' => 'static_pages#Mina'
  get 'Mohamed' => 'static_pages#Mohamed'
  get 'Nada' => 'static_pages#Nada'
  get 'Omar' => 'static_pages#Omar'
  get 'Aboutus' => 'static_pages#Aboutus'

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/bycategory' => 'articles#bycategory', as: :bycategory
  get '/addcategory/:article_id' => 'articles#addcategory', as: :addcategory
  post '/addcategory/:article_id' => 'articles#addcategory2', as: :addcategory2

   

end

TheBlog/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Arcode</a>
    by <a href="/Mohamed">Veegas , <a href="Omar"> Omar , <a href="Nada"> Nada, <a href="Mina"> Mina , <a href="Karim"> Karim , <a href="Merna"> Merna , <a href="Israa">Israa</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

TheBlog/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Arcode",  root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About",   'Aboutus' %></li>
                <% if logged_in? %>
          <li><%= link_to "Blog", articles_path %></li>
             <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
             <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
                  <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

TheBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcode</title>
    
    <% if controller_name == "static_pages_controller"%>
     <%= stylesheet_link_tag "static_pages" %>
     <%= javascript_include_tag 'static_pages', 'data-turbolinks-track' => true %>
     <% else %>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <% end %>
   </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="container">
      <div class="container" style = "background: url(/assets/background.jpg);
    background-size: 100%;">
      <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>