TheBlog/config/routes.rb
Rails.application.routes.draw do

  resources :photos

resources :users

  resources :articles do 
    resources :comments
  end

  root 'static_pages#home'

  get 'static_pages/home' => 'static_pages#home'
  get 'Israa' => 'static_pages#Israa'
  get 'Karim' => 'static_pages#Karim'
  get 'Merna' => 'static_pages#Merna'
  get 'Mina' => 'static_pages#Mina'
  get 'Mohamed' => 'static_pages#Mohamed'
  get 'Nada' => 'static_pages#Nada'
  get 'Omar' => 'static_pages#Omar'
  get 'Aboutus' => 'static_pages#Aboutus'

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/bycategory' => 'articles#bycategory', as: :bycategory
  get '/addcategory/:article_id' => 'articles#addcategory', as: :addcategory
  post '/addcategory/:article_id' => 'articles#addcategory2', as: :addcategory2

   

end

TheBlog/app/models/article.rb
class Article < ActiveRecord::Base
 	has_many :comments,  dependent: :destroy
 	belongs_to :user
 	has_many :photos,  dependent: :destroy

 	has_many :articlecategory, class_name: "ArticleCategory"
	has_many :categories, through: :articlecategory
 	
 	accepts_nested_attributes_for :categories


 	default_scope -> { order(created_at: :desc) }
  
  	validates :title, presence: true,
                    length: { minimum: 5 }
end

TheBlog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	def new
  @article = Article.new
  @category = Category.new
end

def edit
  @article = Article.find(params[:id])
end

def create
  category = Category.find_by_category(params[:article][:category][:category])
  hash = article_params
  hash[:user_id] = current_user.id
  @article = Article.new(hash) 
    if @article.save
      if params[:photos].present?
    params[:photos]['image'].each do |a|
    @photo = @article.photos.create!(:image => a, :article_id => @article.id)
      end
    end

    if category == nil
      category = Category.create(:category => params[:article][:category][:category]) if not params[:article][:category][:category].blank?
    end
    ArticleCategory.create(:article_id => @article.id, :category_id => category.id) if not params[:article][:category][:category].blank?

    redirect_to @article
  else
    render 'new'
    flash[:error] = "Error Creating article"
  end
end



def update
  @article = Article.find(params[:id])
  
  if @article.update(article_params)
     if params[:photos].present?
    params[:photos]['image'].each do |a|
    @photo = @article.photos.create!(:image => a, :article_id => @article.id)
    end
  end
    redirect_to @article
  else
    render 'edit'
  end
end

def index

	if params[:category] != nil
    @article = Category.find_by_id(params[:category][:category]).articles
  else
  @articles = Article.paginate(:page => params[:page], :per_page => 3)
end
end

def show
    @article = Article.find(params[:id])
    @photos = @article.photos.all
    @post_by = User.find_by(id: @article.user_id)
    @comments = @article.comments
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end


def bycategory
  end

  def addcategory
  end

  def addcategory2
    category = Category.find_by_category(params[:category][:category])
    if category == nil
      category = Category.create(:category => params[:category][:category])
    end
    ac = ArticleCategory.find_by(:article_id => params[:article_id], :category_id => category.id)
    ArticleCategory.create(:article_id => params[:article_id], :category_id => category.id) if not ac
    redirect_to article_path(params[:article_id])
  end

private
  def article_params
    params.require(:article).permit(:title, :text, :image)
  end

end

TheBlog/app/helpers/articles_helper.rb
module ArticlesHelper
end

TheBlog/app/views/articles/_article.html.erb
<h3 class= "center">

                   <b><%= link_to article.title, article_path(article) %></b> 
                </h3>
                <p class="lead">
                    by <%= link_to article.user.name, user_path(article.user) %>
                </p>


                <p><span class="glyphicon glyphicon-time"></span> Posted on 
                <%= article.created_at.strftime('%d/%m/%Y, %H:%M') %>
                </p>

                  <% if current_user.admin? %>

                  <span><%= link_to 'Edit', edit_article_path(article), :class => "btn btn-primary", style:"color:white" %></span>
                  <span><%= link_to 'Delete', article_path(article),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", style:"color:white" %></span>

                  <% end %>

                <hr>
                    <div class = "center">
                    <% article.photos.first(1).each do |p| %>
                    <%= image_tag p.image_url, :class => "img-responsive center"%>
                    <hr>
                    </div>
                <% end %>
                <blockquote>
                    <p><%= article.text %></p>
                <%= link_to article_path(article), :class => "btn btn-primary", style:"color:white" do %>
                Read More
                <span class="glyphicon glyphicon-chevron-right"></span>
                <% end %>      
                </blockquote> 
                
                <% if article.categories.present? %>
                <div class = "well well-sm">
                <span>
                <ul class="list-inline">
                <% cats = [] %>
                <% article.categories.each do |c| %>
                <li>
                  <h4>
                  <span class="badge"><%= c.category %></span>
                  </h4>
                </li>
                <% end %>
                </ul>
                </span>
                </div>
                <% end %>
                
<hr>

TheBlog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.fields_for :category do |l| %>
      <%= l.label :category %><br>
      <%= l.text_field :category %>
    <% end %>
  </p>

  <p>
    upload image
    <%= f.file_field :image, :multiple => true, name: "photos[image][]"%>
  </p>
 
  <p>
    <%= f.submit 'Submit Article', :class => "btn btn-primary" %>
  </p>
 
<% end %>

TheBlog/app/views/articles/addcategory.html.erb
<%= form_for :category, :url => addcategory2_path(params[:article_id]) do |f| %>
  <p>
    <%= f.label 'Enter the Category' %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.submit 'Add Category to Article' %>
  </p>
<% end %>

TheBlog/app/views/articles/bycategory.html.erb
<h3 style = "font-family:Times New Roman; color:#A01B00">Select your category</h1>
<%= form_for :category, url: articles_path, method: :get do |f| %>
<div style="width: 200px">
<%= f.collection_select :category, Category.order(:id),:id,:category, class: "btn btn-default dropdown-toggle" %>
</div>
<br>
<div style="width: 200px">
<%= f.submit 'Submit'%>
</div>
<% end %>

TheBlog/app/views/articles/edit.html.erb
<div class = "container">
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path, class: "btn" %>
</div>

TheBlog/app/views/articles/index.html.erb
<div class = "container">
  <div class = "row" >
    <h1 class= "page-header">Blog Posts</h1>
    
    <div class= "btn-group">
    <% if current_user.admin? %>
    <%= link_to 'New article', new_article_path, :class => "btn btn-primary btn-lg", style:"color:white"%> 
    <% end %>
    <%= link_to 'View articles by categories', bycategory_path, :class => "btn btn-primary btn-lg", style:"color:white" %>
      <% @articles.each do |article| %>
      </div>

      <br><br>

      <%= render article%>

      <% end %>
      
      <%= will_paginate @articles %>
  </div>
</div>

TheBlog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

TheBlog/app/views/articles/show.html.erb
                <!-- Blog Post -->

                <!-- Title -->

                <h1><%= @article.title %></h1>

                <!-- Author -->
                <p class="lead">
                by <%= @article.user.name %>
                </p>
                <% if current_user.admin? %>
                <%= link_to 'Back', articles_path,  class: "btn btn-primary" %> 
    
                <span class = "span-right">
                    <%= link_to 'Edit', edit_article_path(@article),  class: "btn btn-primary" %>
                </span>

                <%= link_to 'Add Category', addcategory_path(@article),  class: "btn btn-primary" %>
                 <%= link_to 'Delete', article_path(@article), method: :delete,
              data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              <% end %>

                <hr>
                <!-- Date/Time -->
                <p>
                <span class="glyphicon glyphicon-time"></span>
                Created at <%=@article.created_at.strftime('%d/%m/%Y, %H:%M')%></p>
                <hr>

                <!-- Preview Image -->
                <%= image_tag @article.image_url.to_s if @article.image? %>
                <% @photos.each do |p| %>
                    <%= image_tag p.image_url %>
                    <br><br><br>
                    <hr>
                <% end %>
                

                <!-- Post Content -->
                <p class="lead"><%=@article.text%></p>


                <hr>

                 <span class='st_sharethis_large' displayText='ShareThis'></span>
<span class='st_facebook_large' displayText='Facebook'></span>
<span class='st_twitter_large' displayText='Tweet'></span>
<span class='st_googleplus_large' displayText='Google +'></span>
<span class='st_email_large' displayText='Email'></span>


<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "882ba12b-c172-4e06-8643-87e379f3f1e9", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

                <!-- Blog Comments -->
        
            
                <br>

  				<%= form_for([@article, @article.comments.build]) do |f| %>
                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                            <%= f.text_area :body %>
                            <%= f.submit 'Submit', :class => "btn btn-primary"%>
                            <% end %>
                </div>

                 <% if @comments.count > 0 %>
                
                <%= render @comments %>
            <% end%> 